### PR TITLE
Document rotation

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by retokromer** [comment]
I suggest to add here specular images as well (vertical and/or horizontal flipping), because it’s of the same family.

**Comment by dericed** [comment]
@retokromer I added a new issue for your idea rather than extend the scope of the pr, seehttps://github.com/cellar-wg/matroska-specification/issues/327

**Comment by retokromer** [comment]
@dericed That’s fine with me. Thank you!

**Comment by dericed** [comment]
I'm going to merge as IMHO this pr address https://github.com/cellar-wg/matroska-specification/issues/269. @retokromer if you want please move your comment in https://github.com/cellar-wg/matroska-specification/pull/326#issuecomment-511088866 to a new issue, I'll consider it out of scope with this pr.

**Comment by retokromer** [comment]
@dericed Done in https://github.com/cellar-wg/matroska-specification/issues/330.

**Pull request merged**
