### PR TITLE
use octet rather than byte

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by robUx4** [comment]
I'd rather keep it like that so the text matches the ISOBMFF spec https://aomediacodec.github.io/av1-isobmff/#subsample-encryption

**Comment by retokromer** [comment]
Hmm… Why should our document match one that is less precise?

**Comment by dericed** [comment]
I think that there's important value in having our document matching the referenced one, regardless of our judgement of its precision, in order to not provoke a conflict interpretation in a place where we aspire to simply adopt. I'm aware that the definitions of byte and octet don't completely align, but am very skeptical that AV1 have ever been implemented in an environment with non-octet bytes.
If important, I'd suggest addressing this upstream first, rather than creating a mismatch between the referenced source.

**Comment by JeromeMartinez** [comment]
I am also in favor of keeping the match with "upstream" (here, AV1 specs).

**Comment by retokromer** [comment]
no problem

**Pull request closed without merging**
