### PR TITLE
use legacy and RFC element references HTML anchors

### PR DESCRIPTION
**Pull request by robUx4**
So the internal links generated by the EBML Schema match the RFC and the website.
And we keep the old links alive for external references.

This is needed following #411

### CODE REVIEW

**Comment by robUx4** [comment]
This is missing the (#anchored-element) transformation to HTML links

**Comment by robUx4** [comment]
This XSLT file should probably be maintained outside of this repo.

**Comment by retokromer** [comment]
>This XSLT file should probably be maintained outside of this repo.

Why? And where would you suggest to move it? (I am possibly missing something.)

**Comment by robUx4** [comment]
The website is now generated here https://github.com/Matroska-Org/infrastructure
I'm not sure these files are of any use in the IETF/CELLAR repo.

**Comment by retokromer** [comment]
Thank you for the answer. I was actually missing this and I second the idea to move it.

**Pull request merged**
