### PR TITLE
give an empty default to Targets

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by dericed** [comment]
Updated to address conflict. Do we have consensus that ebml would need an update to address defaults with master elements or not blocking?

**Comment by dericed** [comment]
Just noticed that the EBML spec presently says
> EBML Elements that are Master Elements MUST NOT declare a default value.

So this PR is invalid.

**Comment by robUx4** [comment]
You should open an issue in the EBML specs to discuss if that's something we want or not (it sounds odd to me how to interpret this). Once this is solved we can get back to this.

**Comment by mcr** [comment]
Need to apply solution in EBML to this Element.

**Comment by dericed** [comment]
Closing as EBML will stay with the statement listed in https://github.com/cellar-wg/matroska-specification/pull/334#issuecomment-544293125

**Pull request closed without merging**
