### PR TITLE
Misc automated processing and cleaning

### PR DESCRIPTION
**Pull request by robUx4**
The next step will be to cut lines so it's easier to spot changes in the text. And when the RFC editors make changes we don't have to edit the whole file (see https://github.com/cellar-wg/ebml-specification/commit/6276603f754c51ce0ce77b4d2fd3db95093673f0).

### CODE REVIEW

**Comment by robUx4** [comment]
The build test should work once #399 is merged.

**Comment by retokromer** [comment]
Just out of curiosity: Should it be 72-char lines like in the American teletypewriters? Or 80-char lines like for the 80x24 screens I used when I was teenager?

**Comment by robUx4** [comment]
Neither of these sizes are good in 2020. All text editors can do line wrapping.
The RFC Editor new lines was not even consistent. For now lines shorter than 120 chars should be OK.
It also helps reading changes on Github. It doesn't like long lines.

**Comment by retokromer** [comment]
>All text editors can do line wrapping.

Indeed, my editor displays… the way I can work best.

Reading the code all LGTM; I’ll build it with the other commit on top, before formally approving.

**Comment by retokromer** [comment]
Oops! This was already merged.

**Comment by dericed** [comment]
@retokromer, did you object to the PR?

**Comment by retokromer** [comment]
No, on the contrary, I did test and confirmed that it works fine. While I was testing, it got merged.

**Pull request merged**
